### ISSUE TITLE
RangeError: offset is not uint

### ISSUE THREAD

**Issue by miki131** [DoctorMcKay/node-steam-totp#2]
buffer.js:580
    throw new RangeError('offset is not uint');
          ^
RangeError: offset is not uint
    at checkOffset (buffer.js:580:11)
    at Buffer.readUInt32BE (buffer.js:620:5)
    at Object.exports.generateAuthCode (/home/vagrant/code/node_modules/steam-totp/index.js:24:22)
    at Object.<anonymous> (/home/vagrant/code/steam-bots/checkBot.js:28:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by DoctorMcKay** [comment]
What version of node is this?

**Comment by miki131** [comment]
v0.10.37

**Comment by DoctorMcKay** [comment]
v1.0.1 should fix it. But you should really, _really_ upgrade.

**Comment by miki131** [comment]
Thanks.
