### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by fedorovvldmr** [DoctorMcKay/node-steam-totp#21]
Sometime i get this error:

```
/var/www/mydomain/private/nodejs/node_modules/steam-totp/index.js:129
    return "android:" + Crypto.createHash('sha1').update(steamID.toString()).digest('hex')
                                                                ^

TypeError: Cannot read property 'toString' of undefined
    at Object.exports.getDeviceID (/var/www/mydomain/private/nodejs/node_modules/steam-totp/index.js:129:62)
    at request (/var/www/mydomain/private/nodejs/node_modules/steamcommunity/components/confirmations.js:144:23)
    at SteamCommunity.getConfirmations (/var/www/mydomain/private/nodejs/node_modules/steamcommunity/components/confirmations.js:17:2)
    at /var/www/mydomain/private/nodejs/node_modules/steamcommunity/components/confirmations.js:240:8
    at /var/www/mydomain/private/nodejs/node_modules/steamcommunity/components/confirmations.js:339:3
    at SteamCommunity.<anonymous> (/var/www/mydomain/private/nodejs/steambot.js:2812:8)
    at emitTwo (events.js:87:13)
    at SteamCommunity.emit (events.js:172:7)
    at SteamCommunity._confirmationCheckerGetKey (/var/www/mydomain/private/nodejs/node_modules/steamcommunity/components/confirmations.js:332:7)
    at SteamCommunity.checkConfirmations (/var/www/mydomain/private/nodejs/node_modules/steamcommunity/components/confirmations.js:234:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #472
```

node-steam-totp 1.3.0

**Comment by DoctorMcKay** [comment]
You're calling `getDeviceID()` without a `steamID` argument.
