### ISSUE TITLE
RangeError: index out of range

### ISSUE THREAD

**Issue by motomux** [DoctorMcKay/node-steam-totp#6]
I got following error with v5.2 and v4.2.3

```
error:  RangeError: index out of range

    at checkInt (buffer.js:850:11)
    at Buffer.writeUInt32BE (buffer.js:941:5)
    at Object.exports.getConfirmationKey (/Users/motomu/projects/steam/node_modules/steam-totp/index.js:58:9)
    at Object.<anonymous> (/Users/motomu/projects/steam/libs/steam/trade_user.js:92:27)
    at next (native)
    at onFulfilled (/Users/motomu/projects/steam/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:382:9)
```

**Comment by motomux** [comment]
Sorry, this is because the third parameter `tag` is not a proper value.
