### ISSUE TITLE
Error: Cannot find module 'file-storage'

### ISSUE THREAD

**Issue by Rybczens** [DoctorMcKay/node-steam-totp#8]
Hi. When i was install this script my bot showing Error: Cannot find module 'file-storage'

After install it (npm install file-storage) bow show me:
TypeError: this.storage.readFiles is not a function
    at SteamUser.logOn (/home/koperone/bot_mojnowy steam/node_modules/steam-user/components/logon.js:64:15)
    at Object.<anonymous> (/home/koperone/bot_mojnowy steam/server.js:64:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

**Comment by andrewda** [comment]
This is not an issue with node-steam-totp.

**Comment by DoctorMcKay** [comment]
@andrewda is correct. This module has no dependencies.

That said, you're missing some dependencies. You should probably just do `npm install` to get what you're missing.
